name: Core API CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: tralaai-core-api

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

  deploy:
    name: Deploy Docker to Azure
    runs-on: ubuntu-latest
    needs: build
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.ref == 'refs/heads/main' && github.event.action == 'closed' && github.event.pull_request.merged == true)
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.WEBAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.WEBAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.WEBAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .
          dockerfilePath: ./Dockerfile
          registryUrl: tralaaidocker-f6fxesc2f4fhg5gj.azurecr.io
          registryUsername: ${{ secrets.WEBAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBAPI_REGISTRY_PASSWORD }}
          containerAppName: webapi
          resourceGroup: L1Q4-TralaAI
          imageToBuild: tralaaidocker-f6fxesc2f4fhg5gj.azurecr.io/webapi:${{ github.sha }}
          buildArguments: |
            CALLER_ID=github-actions-v2
